<a href="https://colab.research.google.com/github/TaXueGeXing/Pytorch/blob/main/Deep_Learning_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import torch
import torch.nn as nn
import numpy as np

In [52]:
a = np.ones(5)
b = torch.from_numpy(a)

In [53]:
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


This just a normal test for taking skill for pytorch.

In [54]:
matrix_z = torch.zeros(5, 3)
print(matrix_z)
print(matrix_z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [55]:
matrix_int = torch.ones((5, 3), dtype=torch.int16)
print(matrix_int)
print(matrix_int.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


In [56]:
torch.manual_seed(2024)
matrix_r1 = torch.rand(3, 3)
print(print(f"The seed 2024 \n{matrix_r1}"))

#torch.manual_seed(2024)
matrix_r2 = torch.rand(3, 3)
print(f"The different rand \n{matrix_r2}")

torch.manual_seed(2024)
matrix_r3 = torch.rand(3, 3)
print(f"The same as r1 \n{matrix_r3}")

The seed 2024 
tensor([[0.5317, 0.8313, 0.9718],
        [0.1193, 0.1669, 0.3495],
        [0.2150, 0.6201, 0.4849]])
None
The different rand 
tensor([[0.7492, 0.1521, 0.5625],
        [0.1735, 0.7046, 0.9265],
        [0.4061, 0.3045, 0.9073]])
The same as r1 
tensor([[0.5317, 0.8313, 0.9718],
        [0.1193, 0.1669, 0.3495],
        [0.2150, 0.6201, 0.4849]])


In [57]:
torch.cuda.is_available()

False

这里开始——————————————————————

In [58]:
temp = torch.FloatTensor([23,24,24.5,26,27.2,23])
temp.size()

torch.Size([6])

In [59]:
x = torch.rand(10)
print(x)
x.size()

tensor([0.7492, 0.1521, 0.5625, 0.1735, 0.7046, 0.9265, 0.4061, 0.3045, 0.9073,
        0.7637])


torch.Size([10])

In [60]:
mnist_test = np.loadtxt("/content/sample_data/mnist_test.csv", delimiter=",")
print(mnist_test)
mnist_tensor = torch.from_numpy(mnist_test)
mnist_tensor.size()

[[7. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [4. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]
 [6. 0. 0. ... 0. 0. 0.]]


torch.Size([10000, 785])

In [61]:
n_input, n_hidden, n_output, batch_size = 10, 5, 1, 10


In [62]:
x = torch.randn(batch_size, n_input)
y = torch.tensor([[1.0], [0.0], [0.0], [1.0], [1.0], [1.0], [0.0], [0.0], [1.0], [1.0]])
print(x, y)

tensor([[ 4.1440e-01,  1.8567e+00,  1.9776e+00, -4.3216e-01,  1.3667e+00,
          7.1308e-01, -3.8694e-01, -2.5348e-01, -1.3085e+00,  9.9618e-01],
        [ 9.3908e-01,  1.4148e+00,  6.3434e-01, -7.7645e-02, -1.1175e+00,
         -6.4811e-01,  4.9839e-02,  1.2883e+00, -6.4908e-01, -8.9694e-01],
        [ 1.2634e+00,  3.0576e-02, -5.9316e-01, -5.1539e-01, -1.0767e+00,
         -5.7563e-02, -5.9571e-02,  2.7639e-01, -2.4025e-01,  3.0839e-01],
        [-9.2246e-01, -9.8095e-01,  3.5507e-01,  3.7296e-01, -1.3050e+00,
         -7.9826e-01,  1.0442e+00,  1.1356e+00,  8.4423e-01,  1.4595e+00],
        [-5.6558e-01,  6.9708e-01,  1.2581e-01, -4.3412e-02,  5.3658e-01,
          2.4383e+00, -7.1003e-01,  5.4370e-01,  7.4853e-01,  6.1368e-01],
        [-4.4186e-01,  9.8383e-02, -1.5196e-01, -1.8187e+00, -1.0217e+00,
         -8.2268e-01,  1.5264e+00, -1.8643e-01,  9.1933e-01, -3.2484e-01],
        [ 1.3998e+00, -5.2993e-01, -2.5606e-01,  1.1917e-01, -3.6943e-01,
         -1.1544e+00,  1.1677e+0

In [63]:
# Create a Model
model = nn.Sequential(nn.Linear(n_input, n_hidden),
    nn.ReLU(),
    nn.Linear(n_hidden, n_output),
    nn.Sigmoid())


In [66]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [68]:
for epoch in range(150):
  y_pred = model(x)
  loss = criterion(y_pred, y)
  print(f"eqoch: {epoch} loss: {loss.item()}")
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

eqoch: 0 loss: 0.18252480030059814
eqoch: 1 loss: 0.18147012591362
eqoch: 2 loss: 0.18042410910129547
eqoch: 3 loss: 0.17936810851097107
eqoch: 4 loss: 0.1783471554517746
eqoch: 5 loss: 0.17726300656795502
eqoch: 6 loss: 0.17624486982822418
eqoch: 7 loss: 0.17516344785690308
eqoch: 8 loss: 0.17415255308151245
eqoch: 9 loss: 0.17308659851551056
eqoch: 10 loss: 0.17207112908363342
eqoch: 11 loss: 0.17099925875663757
eqoch: 12 loss: 0.1699923574924469
eqoch: 13 loss: 0.1688951551914215
eqoch: 14 loss: 0.16790731251239777
eqoch: 15 loss: 0.16682711243629456
eqoch: 16 loss: 0.1658381223678589
eqoch: 17 loss: 0.16476412117481232
eqoch: 18 loss: 0.1637546718120575
eqoch: 19 loss: 0.16269049048423767
eqoch: 20 loss: 0.16169556975364685
eqoch: 21 loss: 0.16066832840442657
eqoch: 22 loss: 0.15978467464447021
eqoch: 23 loss: 0.1588870882987976
eqoch: 24 loss: 0.15800337493419647
eqoch: 25 loss: 0.15709111094474792
eqoch: 26 loss: 0.1561712920665741
eqoch: 27 loss: 0.15537802875041962
eqoch: 28 lo